package com.itaSS.interact;

public enum Actions {
    ADD_EXHIBIT, UPDATE_EXHIBIT, ADD_HALL, UPDATE_HALL, ADD_TOUR, UPDATE_TOUR, ADD_WORKER, UPDATE_WORKER, SET_EXHIBIT_TO_HALL, SET_HALLS_TO_TOUR, SET_WORKER_TO_HALL,
    SET_WORKER_TO_TOUR
//    TODO implement these actions:
//    , , SET_DATES_TO_TOUR, SHOW_HALLS_AND_EXHIBITS_IN_TOUR,

}
