package com.itaSS.interact;

public enum Actions {
    ADD_EXHIBIT, UPDATE_EXHIBIT, DELETE_EXHIBIT,
    ADD_HALL, UPDATE_HALL, DELETE_HALL,
    ADD_TOUR, UPDATE_TOUR, DELETE_TOUR,
    ADD_WORKER, UPDATE_WORKER, DELETE_WORKER,
    SET_EXHIBIT_TO_HALL, SET_HALLS_TO_TOUR,
    SET_WORKER_TO_HALL, SET_WORKER_TO_TOUR,
    SHOW_HALLS_IN_TOUR, SHOW_EXHIBITS_IN_TOUR,
    EXIT
//    TODO implement these actions:
// SHOW_HALLS_AND_EXHIBITS_IN_TOUR,

}
